// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBninh_QxJkm9auwn2MMojrNPJX68KTXL0',
    appId: '1:639029668370:web:807fa56bbd9fcb3b7bc6cb',
    messagingSenderId: '639029668370',
    projectId: 'swappyskills',
    authDomain: 'swappyskills.firebaseapp.com',
    storageBucket: 'swappyskills.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGfWXJx-IWQC8-VPYl9SPhdvePzRh0iug',
    appId: '1:639029668370:android:446f0be6cad3431e7bc6cb',
    messagingSenderId: '639029668370',
    projectId: 'swappyskills',
    storageBucket: 'swappyskills.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfiFfgN9CMM6Sw_Njiwyl6TM6p3ch51Ww',
    appId: '1:639029668370:ios:ab7ac9d59f98e7167bc6cb',
    messagingSenderId: '639029668370',
    projectId: 'swappyskills',
    storageBucket: 'swappyskills.firebasestorage.app',
    iosClientId: '639029668370-vv76uv9qijcihda4avgdr89dnrvd9v42.apps.googleusercontent.com',
    iosBundleId: 'com.example.skillSwap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfiFfgN9CMM6Sw_Njiwyl6TM6p3ch51Ww',
    appId: '1:639029668370:ios:ab7ac9d59f98e7167bc6cb',
    messagingSenderId: '639029668370',
    projectId: 'swappyskills',
    storageBucket: 'swappyskills.firebasestorage.app',
    iosClientId: '639029668370-vv76uv9qijcihda4avgdr89dnrvd9v42.apps.googleusercontent.com',
    iosBundleId: 'com.example.skillSwap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBninh_QxJkm9auwn2MMojrNPJX68KTXL0',
    appId: '1:639029668370:web:37eeca67e6e64d347bc6cb',
    messagingSenderId: '639029668370',
    projectId: 'swappyskills',
    authDomain: 'swappyskills.firebaseapp.com',
    storageBucket: 'swappyskills.firebasestorage.app',
  );


}


