name: Flutter CI/CD to Firebase (iOS)

on:
  push:
    branches:
      - flutter
      - main

jobs:
  # --- iOS Build and Firebase Distribution ---
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.5"  # Specify the version of Flutter you're using

      - name: Install CocoaPods (for iOS)
        run: |
          sudo gem install cocoapods
          pod install --project-directory=flutter-project/skill_swap/ios

          
      - name: Install Dependencies
        run: flutter pub get
        working-directory: flutter-project/skill_swap

      - name: Build iOS
        run: flutter build ios --release --no-codesign  # Skip code-signing for testing purposes

      - name: Upload IPA to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: "1:639029668370:ios:ab7ac9d59f98e7167bc6cb"
          token: ${{ secrets.FIREBASE_TOKEN }}  # Using GitHub Secrets for better security
          groups: testers  # You can change this to your Firebase tester group
          file: flutter-project/skill_swap/build/ios/ipa/*.ipa
